from .search_shared import get_search_suggestions, get_search_cards, get_combi_view

def get_search_and_ai_view():
    return """
<sc-if value="{{ is.search }}"><section class="search-panel" aria-label="Search LOUMOO">
<div class="search-actions"><button class="btn btn-secondary" onClick="{{ back }}">Back</button><div class="search-input-wrap">
<input type="search" value="{{ searchQuery }}" onInput="{{ handleSearchInput }}" onKeyDown="{{ handleSearchKey }}" onFocus="{{ searchFocus }}" onBlur="{{ searchBlur }}" onCompositionStart="{{ searchCompositionStart }}" onCompositionEnd="{{ searchCompositionEnd }}" placeholder="Products, stores, services, hotels…" aria-label="Search LOUMOO" role="combobox" aria-autocomplete="list" aria-expanded="{{ searchExpanded }}" aria-controls="search-suggestions" aria-activedescendant="{{ searchActiveOption }}" maxlength="200" autocomplete="off" enterkeyhint="search">
""" + get_search_suggestions() + """
</div><button class="btn btn-primary" onClick="{{ submitSearch }}">Search</button><button class="btn btn-secondary" onClick="{{ clearSearch }}">Clear</button></div>
<div class="search-actions"><button class="btn btn-secondary" onClick="{{ on.voice }}">Voice search</button><button class="btn btn-secondary" onClick="{{ on.threadAi }}">Ask Combi</button><button class="btn btn-secondary" onClick="{{ on.visual }}">Search by photo</button><button class="btn btn-secondary" onClick="{{ on.filters }}">Filters</button></div>
<sc-if value="{{ searchBasic }}"><p role="status">Product search is available. Universal search and Combi are being prepared for this deployment.</p></sc-if>
<sc-if value="{{ searchAdvanced }}"><div class="search-actions"><label class="search-grow">Search in<select value="{{ searchType }}" onChange="{{ setSearchType }}"><option value="all">Everything</option><option value="product">Products</option><option value="service">Services</option><option value="store">Stores</option><option value="hotel">Hotels</option><option value="travel">Travel</option><option value="announcement">Announcements</option></select></label><label class="search-grow">Sort by<select value="{{ searchSort }}" onChange="{{ setSearchSort }}"><option value="relevance">Relevance</option><option value="recent">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="rating">Rating</option></select></label></div></sc-if>
<sc-if value="{{ searchBusy }}"><p role="status">Searching the catalog…</p></sc-if><sc-if value="{{ searchError }}"><p role="alert" class="search-error">{{ searchError }}</p><button class="btn btn-secondary" onClick="{{ retrySearch }}">Retry search</button></sc-if>
<sc-if value="{{ searchHasResults }}"><p role="status">{{ searchTotal }} results</p>
""" + get_search_cards() + """</sc-if>
<sc-if value="{{ searchHasNoResults }}"><div class="search-empty"><h3>No matches yet</h3><p>Try a shorter term, another city, or fewer filters.</p><button class="btn btn-secondary" onClick="{{ on.filters }}">Adjust filters</button></div></sc-if>
<sc-if value="{{ searchHasMore }}"><button class="btn btn-secondary" disabled="{{ searchMoreBusy }}" onClick="{{ loadMoreSearch }}">Load more results</button></sc-if><sc-if value="{{ searchMoreBusy }}"><p role="status">Loading more…</p></sc-if>
<sc-if value="{{ searchIsDefault }}"><h3>What are you looking for?</h3><p>Search in French or English, or ask Combi to narrow it down.</p><div class="search-actions"><button class="btn btn-secondary" onClick="{{ () => runSearch('ordinateur') }}">Ordinateurs</button><button class="btn btn-secondary" onClick="{{ () => runSearch('hotel') }}">Hotels</button><button class="btn btn-secondary" onClick="{{ () => runSearch('reparation') }}">Repair services</button></div></sc-if>
<sc-if value="{{ searchHasRecent }}"><h3>Recent searches</h3><div class="search-actions"><sc-for list="{{ searchRecent }}" as="term"><button class="btn btn-secondary" onClick="{{ () => runSearch(term) }}">{{ term }}</button></sc-for><button class="btn btn-secondary" onClick="{{ clearRecentSearches }}">Clear history</button></div></sc-if>
</section></sc-if>
<sc-if value="{{ is.filters }}"><section class="search-panel" aria-label="Search filters"><div class="search-actions"><button class="btn btn-secondary" onClick="{{ back }}">Back</button><h2>Refine your search</h2><button class="btn btn-secondary" onClick="{{ resetFilters }}">Reset</button></div>
<label>City<input value="{{ filterCity }}" onInput="{{ setSearchCity }}" maxlength="80" placeholder="Any city"></label><div class="search-actions"><sc-for list="{{ searchCities }}" as="place"><button class="{{ place.className }}" onClick="{{ () => setFilterCity(place.city) }}">{{ place.city }}</button></sc-for></div>
<label class="search-check"><input type="checkbox" checked="{{ filterVerifiedOnly }}" onChange="{{ toggleVerifiedOnly }}">Verified providers only</label>
<sc-if value="{{ searchAdvanced }}"><div class="search-actions"><label class="search-grow">Minimum price (XAF)<input type="number" min="0" max="10000000000" value="{{ filterMinPrice }}" onInput="{{ setFilterMinPrice }}" inputmode="numeric"></label><label class="search-grow">Maximum price (XAF)<input type="number" min="0" max="10000000000" value="{{ filterMaxPrice }}" onInput="{{ setFilterMaxPrice }}" inputmode="numeric"></label></div>
<label>Condition<select value="{{ filterCondition }}" onChange="{{ setFilterCondition }}"><option value="">Any condition</option><option value="new">New</option><option value="used_like_new">Used, like new</option><option value="used_good">Used, good</option><option value="pre_owned">Pre-owned</option><option value="refurbished">Refurbished</option></select></label>
<label class="search-check"><input type="checkbox" checked="{{ filterInStock }}" onChange="{{ toggleSearchStock }}">Confirmed available only</label><p>Hotel prices are starting rates. Choose dates on the hotel page to check availability.</p></sc-if>
<button class="btn btn-primary" onClick="{{ applyFilters }}">Show results</button></section></sc-if>
<sc-if value="{{ is.voice }}">""" + get_combi_view(True) + """</sc-if>
<sc-if value="{{ is.visual || is.visualScan || is.visualResults }}"><section class="search-panel" aria-label="Photo search"><div class="search-actions"><button class="btn btn-secondary" onClick="{{ back }}">Back</button><h2>Search by photo</h2></div>
<p>Choose an object photo to find possible catalog matches. We use an AI description of the image; results are not guaranteed to be the exact model.</p>
<sc-if value="{{ visualAvailable }}"><label>Choose a photo (JPEG, PNG or WebP, up to 1 MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange="{{ searchPhoto }}" disabled="{{ visualBusy }}"></label><p>The image is sent to our AI provider for this search. Avoid private documents or personal information.</p></sc-if>
<sc-if value="{{ !visualAvailable }}"><p role="status">Photo search is not available in this deployment yet.</p></sc-if><sc-if value="{{ !isLoggedIn }}"><button class="btn btn-secondary" onClick="{{ on.signIn }}">Sign in to search by photo</button></sc-if>
<sc-if value="{{ visualHasPreview }}"><img class="search-photo-preview" src="{{ visualPreview }}" alt="Your selected search photo" loading="lazy" decoding="async"></sc-if><sc-if value="{{ visualBusy }}"><p role="status">Looking for possible matches…</p></sc-if><sc-if value="{{ visualError }}"><p role="alert" class="search-error">{{ visualError }}</p></sc-if>
<sc-if value="{{ visualHasResults }}"><h3>Possible matches</h3><p>{{ visualMessage }}</p>""" + get_search_cards('visualCards') + """</sc-if>
<sc-if value="{{ visualNoResults }}"><p role="status">No catalog matches found. Try a clearer photo or search by name.</p></sc-if><button class="btn btn-secondary" onClick="{{ on.search }}">Search by typing</button></section></sc-if>
"""
